version: "2"

services:
  nginx:
    container_name: sidca-ensemble_container
    image: ensemble/nginx
    restart: always
    build: .
    environment:
      - NGINX_TEMPLATE=nginx
      - NGINX_SERVER_NAME=sidca-ensemble
      - NGINX_SERVER_PORT=8080
      - NGINX_FILE_LOG=sidca-ensemble.log
      - NGINX_NODE_1=172.16.1.98:1980
      - NGINX_NODE_2=172.16.1.119:1980
      - NGINX_URL=fleni.evr.servicios.EsbWSSoap
    ports:
      - "8080:8080"
    volumes:
      - ngnix-storage:/var/log/nginx
    networks:
      - nginx-tier

volumes:
  ngnix-storage:
    driver: local

networks:
  nginx-tier:
    driver: bridge